version: '3.8'

services:
  # Base de Datos Vectorial (Memoria de Abunda)
  qdrant:
    image: qdrant/qdrant
    container_name: abunda_vector_db
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  # Cola de Mensajes (Para tareas pesadas)
  redis:
    image: redis:alpine
    container_name: abunda_queue
    ports:
      - "6379:6379"

  # Nota: El servicio de API (Python) se correr√° localmente para desarrollo
  # usando: uvicorn main:app --reload